### ISSUE TITLE
Check email send succesfully not possible.

### ISSUE THREAD

**Issue by unicode-it** [CZ-NIC/envelope#12]
Docstring of send-method: `To check e-mail was successfully sent, cast the returned object to bool.`

Expected behaviour: 

```
check = Envelope().send()
if not check:
    raise SomeException
```
Should raise SomeException if send fails.

Actual behaviour:

No way to check if sending was succesfull. No Exception raised.

**Comment by unicode-it** [comment]
See pull request.

**Comment by e3rd** [comment]
Hi, could you please further prove actual behaviour does not work? It seems to my `SomeException` is correctly raised when sending fails now. Thanks!

**Comment by unicode-it** [comment]
I tried the following:
I set a wrong sender address to test it. The smtp server refused to send the mail. The error was correctly logged via logger. But the check still evaluated to true.
I actually oversaw the implementation of __bool__ method, but still it does not evaluate to false even though the message is not send.

**Comment by e3rd** [comment]
> check still evaluated to true

Post the code you've tried please. I wonder to see how come it evaluated to True.

```python
from envelope import Envelope
e = Envelope("dummy")
print(bool(e))  # False

e.to("test@example.com")
print(bool(e))  # False

e.sender(False)
e.send()
print(bool(e))  # False
```

**Comment by e3rd** [comment]
No reaction, closing for now
