### ISSUE TITLE
Make it possible to specify GNUPGHOME

### ISSUE THREAD

**Issue by unicode-it** [CZ-NIC/envelope#13]
Currently a custom GNUPGHOME can only be supplied to Envelope by overriding private method `_get_gnupg_home`.

**Comment by unicode-it** [comment]
I can provide a pull request, if wanted...

**Comment by e3rd** [comment]
use `.gpg(HOME)` in Python or export `GNUPGHOME` variable in Bash :)

**Comment by unicode-it** [comment]
Thank you for explaining. It is even in the readme. Sry for opening this issue.
