### ISSUE TITLE
newer version seems to break the old usage

### ISSUE THREAD

**Issue by aaronkaplan** [CZ-NIC/envelope#15]
Old usage:

```python
smtp_from = "root@example.com"
body = """...some text ..."""
envelope.envelope()\
        .message(body)\
        .subject(subject)\
        .to(email)\
        .sender(smtp_from)\
        .smtp("localhost")\
        .send()
```

--> error message:

```
Traceback (most recent call last):
  File "/home/aaron/foo.py", line 45, in <module>
    send_email_api_key("aaron@lo-res.org", "1234", 10)
  File "/home/aaron/foo.py", line 35, in send_email_api_key
    envelope.envelope()\
TypeError: 'module' object is not callable
```

# Problem identification

```python
envelope.Envelope()\
   ...
```

works. Note that the second "E" is capitalized.

# How to fix it?

Hard to tell, maybe for backwards compatibility some warning should be issued if someone calls it the old way 
with a small "e" ?

**Comment by aaronkaplan** [comment]
Big hi goes to @e3rd

**Comment by e3rd** [comment]
from envelope import Envelope

Helooo

**Comment by aaronkaplan** [comment]
yes :) thanks. I got it. 
I wanted to point out that there seems to have been a change at some point where 
```python

envelope.envelope(). \ 
  ...
  .send()
```

worked. But since some time (some change) it does not, since it's capitalized now.
So, basically this breaks old code.

My suggestion is to create a warning that the (lower caps) version is deprecated.


re:hi :)

**Comment by sebix** [comment]
I guess the change was in 48161f481a92a3048c66cc38f8ce55b6618111db (March 2020)

**Comment by e3rd** [comment]
Hello, we had bank holidays back then so I've read the initial issue too quickly.

Yeah I know about this change. I thought long and hard about the import statement. But since it happened before the version 1.0.0, you were one of the first users when the application was still in development and we presented the PR more broadly after the 1.0.0 release, I prefer to let it sleep :)

**Comment by aaronkaplan** [comment]
yes, makes sense. Thanks.
