### ISSUE TITLE
Allow setting Return-Path (Envelope From) independently

### ISSUE THREAD

**Issue by hege-li** [CZ-NIC/envelope#16]
In a nutshell my Postfix filter script works like this:

Envelope().load(sys.stdin.buffer.read()).encryption(key=foobar).smtp().send()

Postfix provides original Envelope From as Return-Path header.

But Envelope calls smtplib.send_message() without from_addr parameter, which results in new Return-Path generated from From: header:

https://docs.python.org/3/library/smtplib.html#smtplib.SMTP.send_message
> If from_addr is None or to_addrs is None, send_message fills those arguments with addresses extracted from the headers of msg as specified in RFC 5322: from_addr is set to the Sender field if it is present, and otherwise to the From field.

So only workaround is to set Sender: header, but this is ugly and not desirable as now Outlook will display stuff like "sender@header represents user from@header" etc.

Please allow setting smtplib.send_message() from_addr parameter somehow. Or maybe provide some option to reuse original Return-Path automatically for this.

**Comment by e3rd** [comment]
Hi,
* your From header differs from the envelope From?
* share a piece of code you'd like to set from_addr with, using an API that does not yet exist as a proposal
* please publish some example message you receive and re-post so that I can think about it

**Comment by hege-li** [comment]
> Hi,
> 
>     * your From header differs from the envelope From?

Of course. The headers are meant for different purposes and this is normal situation, when bounces are needed to be processed separately etc.

>     * share a piece of code you'd like to set from_addr with, using an API that does not yet exist as a proposal

There is already .from_() and .sender(), perhaps add .envelope_from() ?

**Comment by e3rd** [comment]
What about current master, would that suit you? I've named it `from_addr()` so that it is the same as the smtplib parameter. Do you find it a good idea please?

**Comment by e3rd** [comment]
Seems so.
