### ISSUE TITLE
Hardcoded timeout leads to error

### ISSUE THREAD

**Issue by tna76874** [CZ-NIC/envelope#20]
The timeout for the smtp connection is hardcoded on 1 second.

`smtplib.SMTP(self.host, self.port, timeout=1)`

When I try to attach a file with a certain size, here is a point (something between 1 and 1.4MB) where the sending fails.

I would suggest to set the timeout as an parameter!

**Comment by e3rd** [comment]
(thanks! I have not tested with larger mails, I'll add something like it)
