### ISSUE TITLE
Correct handling of failed send (and re-tries)

### ISSUE THREAD

**Issue by s-m-e** [CZ-NIC/envelope#21]
First of all, **amazing** package. Thanks a lot!

I am sending e-mail from some cloud server via the host provider's well established SMTP server. For some reason, in about 1 out of 10 times, the sending fails. I want to handle those cases correctly (and add some logging, so I can see what happened). At the moment, I am calling `envelope` as follows:

```python
Envelope(
    msg
).subject(
    subject
).sender(
    sender
).reply_to(
    reply_to
).to(
    to
).encryption(
    key = True,
).smtp(
    server,
    port,
    user,
    pwd,
    "starttls",
).send()
```

If I understand correctly, the `send` method returns `False` if something happened. Based on that, I could imagine the following implementation (with some kind of async timer instead of the dull `sleep` etc):

```python
from time import sleep

important = Envelope(
    msg
).subject(
    subject
).sender(
    sender
).reply_to(
    reply_to
).to(
    to
).encryption(
    key = True,
).smtp(
    server,
    port,
    user,
    pwd,
    "starttls",
)

def send_mail(email, max_tries = 10, delay = 60):
    counter = 0
    while True:
        result = email.send() # Can I call `send` multiple times?
        if bool(result): # Do I need this conversion?
            return
        counter += 1
        # TODO log result and details here if possible
        if counter >= max_tries:
            break
        sleep(delay)
    # TODO log that max tries where attempted
    raise SystemError('sending email failed')

send_mail(important)
```

- Can I safely call `send` multiple times on a single mail object? Notice that the email is in fact supposed to be GPG encrypted.
- Is there a way to get additional information on what happened if sending failed so I can log it?
- Have I overlooked something, i.e. can `envelope` do all of that on its own (in a thread perhaps)?

**Comment by sebix** [comment]
>     * Is there a way to get additional information on what happened if sending failed so I can log it?

The errors are hidden in the logs (if level is warning or lower):
https://github.com/CZ-NIC/envelope/blob/e5806d0441839dfab3f79057231623e9c8498c1d/envelope/envelope.py#L1098-L1102

I think these fatal errors should raise exceptions, so that they can be handled by the calling code. Just my 5 cents

**Comment by s-m-e** [comment]
Interesting, thanks. I had the following show up in my system's log yesterday:

```
Jan 15 21:30:22 computer gunicorn[22735]: SMTP sending failed.
Jan 15 21:30:22 computer gunicorn[22735]: Connection unexpectedly closed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2635)
```

and

```
Jan 15 21:31:13 computer gunicorn[22735]: SMTP sending failed.
Jan 15 21:31:13 computer gunicorn[22735]: please run connect() first
```

I am using this as part of a web application running via `gunicorn`, which in return logs to the syslog. In the above two cases, I know for sure that sending the exact same data worked a few minutes before and a few minutes after. Both cases did **not** raise an exception. This does not match what I would expect to see in the log based on the code you have highlighted, @sebix.

**Comment by sebix** [comment]
> Both cases did **not** raise an exception.

I did not mean that the code actually does it. Just that I think the cleaner, more pythonic behaviour of envelope would be if it raised exceptions (which it doesn't).

**Comment by s-m-e** [comment]
@sebix Sry, my mistake. Yes, they should. But then if the above is established behavior that people have been relying on, I'd rather introduce an extra parameter into the `send` method, e.g. `fail_fatal = False` which, if set to `True`, would cause exceptions.

**Comment by s-m-e** [comment]
Digging a bit into it, there actually is some [re-try code](https://github.com/CZ-NIC/envelope/blob/e5806d0441839dfab3f79057231623e9c8498c1d/envelope/utils.py#L348) in the `utils.SMTP` class. This is [where my log is coming from](https://github.com/CZ-NIC/envelope/blob/e5806d0441839dfab3f79057231623e9c8498c1d/envelope/utils.py#L366).

**Comment by s-m-e** [comment]
Just go another one:

```
Jan 16 18:15:17 computer gunicorn[23105]: SMTP sending failed.
Jan 16 18:15:17 computer gunicorn[23105]: Connection unexpectedly closed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2635)
Jan 16 18:16:56 computer gunicorn[23105]: SMTP sending failed.
Jan 16 18:16:56 computer gunicorn[23105]: please run connect() first
Jan 16 18:18:18 computer gunicorn[23105]: SMTP sending failed.
Jan 16 18:18:18 computer gunicorn[23105]: please run connect() first
```

This is actually at least one distinctive bug: If sending of a first email fails with `Connection unexpectedly closed`, the connection remains cached in `utils.SMTP._instances`. If one **subsequently** tries to use this cached connection for sending a second, independent email, one gets `please run connect() first` as expected: The disconnected connection object is still cached. I got around this earlier because I was very often restarting my application for debugging.

On a second note, the cache does not drop "old" connections or ones that "died of natural causes". They might simply time-out in a long-running application for instance, causing the exact same behavior.

There might be a third bug in here: `SSL: WRONG_VERSION_NUMBER` happens, but not reproducible. Sometimes, it just works. Maybe there is some load balancing happening on my SMTP server with nodes using different TLS settings, but ... hard to imagine. I am using `starttls` via port `587` - it's "mostly" working. Either way, SSL-handling needs to be improved or even exposed to the user via optional parameters (e.g. `ssl_version`), see [here](https://stackoverflow.com/a/57709946/1672565) for instance.

On top of the above, `for attempt in range(1, 3)` is nice but has its downsides. It's only two attempts, hard-coded. Besides, the second attempt is not delayed. Assuming that the number of attempts becomes a parameter, the delay could also be an optional parameter to avoid landing you a spot on a black list ...

**Comment by e3rd** [comment]
(guys, thanks a lot for the activity, busy, I'll get back to you)

**Comment by e3rd** [comment]
I hope I reacted to all of the thoughts.

> Can I safely call send multiple times on a single mail object? Notice that the email is in fact supposed to be GPG encrypted.

I think so. Why would you do that? Are you changing recipients in the meantime?

> if bool(result): # Do I need this conversion?

No, it's implicit.

> SSL-handling needs to be improved or even exposed to the user

You may pass your custom SMTP object to the .smtp() function https://github.com/CZ-NIC/envelope/#sending and handle it freely. If you find up something, I'll be glad if you share your thoughts here in the issue tracker in order to make Envelope better.

My tasks:
* [ ] `for attempt in range(1, 3)` -> make it 3 attempts
* [ ] parameter attempts=3
* [ ] parameter delay
* [ ] parameter timeout #20
* [ ] `fail_fatal = False` vs status quo vs raise exceptions instead of `if failures: -> warning` consider
* [ ] explore `SMTP fails -> run connect() first` keep failed connection vs discard it

**Comment by sebix** [comment]
> `for attempt in range(1, 3)` -> make it 3 attempts

use `range(3)`. Last value is exclusive.

**Comment by s-m-e** [comment]
> I think so. Why would you do that? Are you changing recipients in the meantime?

No, I am having SMTP errors ;) Initially, I wanted to implement the re-try code myself until I discovered that there is re-try logic within Envelope. I'd cache the Envelope object and submit it to an async scheduler with a defined delay so my app can go on and do its thing in the meantime.

> You may pass your custom SMTP object [...]

I have seen that. One of the reasons why I tried (and love) Envelope is that I do not need to deal with the SMTP object and related stuff. Envelope nicely hides this stuff. The problem is that it does not handle SMTP errors properly - then it would be perfect.

> parameter delay

One thought here: Do not go for something like `time.sleep` - it simply blocks the thread and does not really allow another thread to run at the same time (within Python at least, thanks to the GIL). There is not ONE specific way to implement a delay, it really depends on the user's application. In Envelope, I'd rather implement it in such a way that the user code can handle the re-try via whatever mechanism make sense in a given app. I am thinking of async schedulers etc. I could imagine a re-try count exposed at the `Envelope` class and a dedicated exception that a user can catch if a retry failed. A retry could then simply be triggered by calling `send` another time while `Envelope` takes care of the annoying stuff like reopening a failed SMTP connection etc.

**Comment by s-m-e** [comment]
@e3rd If you have a specific idea on how to move this forward I'd wait for your implementation. At the moment, I have code relying on SMTP etc working reliably it which needs fixing until next week so I'd provide you with a PR by the end of the weekend otherwise :)

**Comment by e3rd** [comment]
> and does not really allow another thread to run at the same time

I don't think so – take a look at the following code. It clearly demonstrates sleep won't blocks other threads.

```python3
import threading
from time import sleep

def x():
    sleep(1)
    print("t1")
    
def y():
    print("t2")

t1 = threading.Thread(target=x)
t1.start()
t2 = threading.Thread(target=y)
t2.start()

# output: t2, t1
```

I've implemented with sleep with default value delay=0 for now. Do you know anything more generic?

> re-try count exposed

Good idea. What about this simple `attempts` exposed API?

```python3
e = Envelope("mesage").smtp(attempts=5).send()
if not e:
    # re-try mechanism for the case localhost:25 would decline 5 times
```

What exception should be raised if the `if not e` is not enough and what info should it tell? The changes are at current master https://github.com/CZ-NIC/envelope/commit/4260bf3e6a2e533f4d107dfc2ea61810138e0e44#diff-4618d9320f0da8f05cfd40b9ac285137c880e39df23ba8461056620f93d0433dR355

Thanks for the ideas! :)

**Comment by s-m-e** [comment]
> I don't think so – take a look at the following code. It clearly demonstrates sleep won't blocks other threads.

Interesting. I have seen adverse effects but the the use cases were a little bit more complex. I have just checked: On paper, it does release the GIL. If it works, keep going ...

> Do you know anything more generic?

Not generic in a general sense. Doing a pure threading approach hidden in your library is kind of bad for the `asyncio` and `twisted` crowds. In those cases, you want to follow completely different paradigms. That's why I suggested to let the user code handle the retry (by simply allowing to call `send` again) and raise a special exception of the one individual attempt failed. Something along the following lines:

```python
import asyncio
LOOP = asyncio.get_event_loop()

email = Envelope(...)

async def send(email, loop):
    if email.smtp_retry > 0:
        asyncio.sleep(email.smtp_delay)
    email.smtp_retry += 1
    if email.smtp_retry >= email.smtp_retrymax:
        log('something went wrong')
        return
    try:
        email.send()
    except EnvelopeSmtpFailed:
        loop.create_task(retry_send(email, loop))

LOOP.create_task(retry_send(email, loop))
```

Technically, you could also wrap this into Envelope by offering an additional `send_async` method.

> Thanks for the ideas! :)

You're welcome.

**Comment by e3rd** [comment]
> simply allowing to call `send` again

possible

I might be blind or ignorant some useful paradigms but I don't see much difference between your code and this code that can be done without raising exceptions.

```python3
import asyncio
LOOP = asyncio.get_event_loop()

email = Envelope(...).smtp(attempts=SMTP_ATTEMPTS, delay=SMTP_DELAY)

async def retry_send(email, loop = None):
    if not email.send():
        log('something went wrong')
        return        

LOOP.create_task(retry_send(email, LOOP))
```

Is the advantage in your code that the main program do not wait the SMTP connection is made and thus runs faster?
If you need so detailed control in the e-mail sending, isn't it better to handle an SMTP connection manually? (If we defaulted an async version of sending, user might end up flooding its SMTP server.)  
Are not timeout=, attempts=, and delay= options I exposed last week of the .smtp() method already covering your needs? :)

The core thought behind the envelope project was that the user could trust the library to provide anything without the need to catch various undocumented exceptions (as I've seen in other projects) to ensure the library usage won't melt down whole program.  
If envelope is to start raising exceptions, following questions should be answered:
* .send() method is not the only one that finalize Envelope object. .encrypt() and sign.()
	* Should these have fail_send parameter too?
* why not re-raise original smtplib.SMTPException
* shouldn't rather log messages have the possibility to be muted? I can't help myself, I find `bool(envelope.send())` the most elegant way to know if the e-mail was sent or not.

**Comment by e3rd** [comment]
(If no objections given, I'll close this comment as solved by the new parameters I've added before and release a new version.)

**Comment by s-m-e** [comment]
@e3rd If you can give me until tomorrow afternoon, I'll review them. Sorry, this was pushed down my todo list ...

**Comment by e3rd** [comment]
I might wait weeks if that helped, no prob :)

**Comment by e3rd** [comment]
If you ever have time to process this, we'll reopen the ticket.
