### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by sebix** [CZ-NIC/envelope#23]
Congrats to the 2.0.0 release!

I noticed that you created just the commit, but not a specific tag on this commit. 
Is this intentional? (Maybe you just forgot to push the tag). Creating a tag and a release on GitHub gives the stable version more visibility.

**Comment by e3rd** [comment]
Thanks for that! Would you be please so kind and explain or point me to any source concerning project workflow claiming that releasing on GitHub too (apart from PyPi) gives an advantage?

**Comment by sebix** [comment]
With the tags in the repos, other potential contributors, developers and also users can easily track which commit corresponds to which version (useful for diffing/comparing, making changes, installing via git etc). This is my main concern

The GitHub releases do not add much value, except clearer visibility of the releases in the UI, not important (but easy to do though).

**Comment by sebix** [comment]
Cool, thanks
