### ISSUE TITLE
Signing fails for non-English locales

### ISSUE THREAD

**Issue by fruchti** [CZ-NIC/envelope#24]
Using `.signature()` would always fail for me with `The secret key for XXX seems to not be used, check if it is in the keyring: gpg --list-secret-keys`. It turned out to be `_sign_gpg_now()` looking for a particular string in gpg’s output, which of course isn’t there if the system’s locale is different.

As a workaround I added
```python
from os import environ
environ['LC_ALL'] = 'C'
```
to my script, but maybe there’s a better way (since that changes the locale for all subprocesses, which is likely unexpected).

**Comment by e3rd** [comment]
Sorry for that bothersome bug, I'll investigate (probably not earlier than next week)

**Comment by e3rd** [comment]
Will you please try current solution? We set the default locale only to the underlying `gpg` subprocess there.

**Comment by e3rd** [comment]
It's difficult to set locale to the underlying library only as it does not support it, I'll have to investigate more.

**Comment by e3rd** [comment]
Reference to https://github.com/vsajip/python-gnupg/pull/186

**Comment by e3rd** [comment]
A feature has been expressively merged to the 3rd party library. When they release, we'll promptly fix this.

**Comment by e3rd** [comment]
Would you please check current master works? :)

**Comment by e3rd** [comment]
No reaction, I suppose it works well then.

**Comment by fruchti** [comment]
Hi, sorry for the late reply. I had completely forgotten about the issue after adding the workaround I suggested above.

I just now checked everything with the new release and everything is working as expected. Thanks a lot for the very thorough fix!

**Comment by e3rd** [comment]
Cool, thanks :)
