### ISSUE TITLE
Dual SMIME & PGP signing?

### ISSUE THREAD

**Issue by Manouchehri** [CZ-NIC/envelope#28]
Is it possible to have a message signed with both S/MIME and PGP?

After playing a bit with nested `application/pkcs7-signature` and `application/pgp-signature`, I can't seem to find a way of making both Gmail and ProtonMail happy.

**Comment by e3rd** [comment]
I didn't think of this usecase. If I have time, I may try to give a prototype of this the next week so that you can see whether this works. Then, we'll think of an API (which I tend to keep as simple as possible).

**Comment by e3rd** [comment]
Can you elaborate more? Gmail wants which and ProtonMail wants which?

I've made a prototype for you. It is now temporarily possible to make up messages signed both with smime and pgp.

```
e = Envelope(MESSAGE)  # put message here
smime_key = Path("tests/smime/key.pem").read_bytes()  # put key here
e._cert = Path(self.smime_cert).read_bytes()  # put cert here
e = (e
                .smime(signature_experimental=smime_key)
                .gpg(GNUPG_HOME)
                .subject("my subject")
                .reply_to("test-reply@example.com")
                .signature() # Path("tests/smime/key.pem"), cert=Path(self.smime_cert))
                .send(False))
print(e)
```

**Comment by e3rd** [comment]
If you ever have time, try the piece of code to confirm whether it suits your needs, we'll reopen the issue then.
