### ISSUE TITLE
Introducing types?

### ISSUE THREAD

**Issue by mcarpenter** [CZ-NIC/envelope#31]
Hi,

Would the project consider introducing types?

Concretely, Pyright complains about `nl2br` in calls such as:

```python
            envelope = Envelope(html_body)             \
                    .mime(subtype='html', nl2br=False) \  # here
                    .subject(subject)                  \
                    .from_(from_addr)                  \
                    .to(to_addr)                       \
                    .smtp(host, port)
```

because the inferred type of parameter `nl2br` is `str` (the default is `constants.AUTO = "auto"`). Other intended values are type `bool` (as above) but type checkers cannot infer this from the `mime()` function definition.

The simplest solution would be to declare the type of this parameter `Union[str, bool]`. That's a bit sloppy in that it admits any string (not just `"auto"`) but it would eliminate the type error and would not impact existing consumers.

Alternatively we could introduce an `Enum`, with keys say `Nl2br.AUTO`, `Nl2br.ALWAYS`, `Nl2br.NEVER` with values as they are currently defined. This would make for happier type checking and also not impact existing consumers.

I'd be happy to submit a small PR if you find one of these approaches acceptable.

(Python 3.10.12, pyright 1.1.347, envelope 2.0.2)

**Comment by e3rd** [comment]
It would be great, thanks! What about `typing.Literal`, something like `nl2br: Literal["auto"] | bool` (but both your ideas seem good to me too)

**Comment by e3rd** [comment]
No reaction – I've implemented it with the Literal. Feel free to reopen.
