### ISSUE TITLE
Signature: The message contents may have been altered. if using attachment

### ISSUE THREAD

**Issue by T0jgli** [CZ-NIC/envelope#34]
Hi,

I have a small problem using the signing method with attachment.

```python
cert = open("/home/cert/emailsigning.cert", "r")
key = open("/home/cert/emailsigning.key", "r")

Envelope().message(content).attach(attach, name="example.xlsx").subject("Subject").to(TO).from_("from@example.com").smtp("smtp.example.com", 25, os.environ.get("SMTP_USERNAME"), os.environ.get("SMTP_PASSWORD"), "starttls").signature(key=key.read(), cert=cert.read()).send()
```

If I add any attachment, the signature verification says "The message contents may have been altered". Without any attachment everything is valid.
I tried to use the one-liner method and tried to place attachment to the end of the line after the signature, but same error.

I am using Outlook btw.

**Comment by e3rd** [comment]
Strange!
(Using one-liner does no change, as the attachments are effectively attached when sending.)

Could you explain how do you use Outlook? (I can't get it how Outlook can be related when sending with Python through Envelope.)

**Comment by T0jgli** [comment]
Managed to fix it, by specifying the correct mime type to the attachment:
Correct command looks like this:
```python
Envelope().message(content).attach(path=filepath, name="filename.xlsx",mimetype="application/vnd.ms-excel").subject("Subject").to(TO).from_("from@example.com").smtp("smtp.example.com", 25, os.environ.get("SMTP_USERNAME"), os.environ.get("SMTP_PASSWORD"), "starttls").signature(key=key.read(), cert=cert.read()).send()
```

**Comment by e3rd** [comment]
Strange! Thanks for having investigated, I'll try to consider this in the new release.

**Comment by e3rd** [comment]
I did a thorough testing but no matter what I have not been able to reproduce an unsuccessful verification. 
I'd be glad if you could try again with the testing key you'll find in the repository at https://github.com/CZ-NIC/envelope/tree/master/tests/smime .

```python
from envelope import Envelope

smime_cert = 'envelope/tests/smime/cert.pem'
smime_key = 'envelope/tests/smime/key.pem'
e = (Envelope("dumb message")
                         .smime()
                         .subject("my subject")
                         .attach(path=Path("file.xlsx"))
                         .reply_to("test-reply@example.com")
                         .sign(smime_key, cert=Path(smime_cert))
    )
Path("/tmp/message.eml").write_text(str(e))
```

```bash
openssl smime     -verify  -in /tmp/message.eml -inkey key.pem -certfile cert.pem  -noverify
```
