### ISSUE TITLE
Question on how to manage refused senders

### ISSUE THREAD

**Issue by cmh716** [CZ-NIC/envelope#35]
My email server will occasionally refuse my email.  The response is almost instantaneous, with a 421 (under 1 second).  If I send it again, it works fine.

SMTP sender refused, unable to reconnect. (421, b'4.4.2 qs51p00im-qukt01071702.me.com Error: timeout exceeded', 'myemail@icloud.com')

envelope doesn't seem to be timing out or retrying because I have it set to:
.smtp(SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, "starttls", timeout=45, attempts=5, delay=10)

Would you happen to have any tips to help with this issue?  Thanks.  I love this project.

**Comment by e3rd** [comment]
Please explain

> envelope doesn't seem to be timing out or retrying because --**I have it set to**--:
`.smtp(SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, "starttls", timeout=45, attempts=5, delay=10)`

It seems to me you did not set it to no retry, but to retry 5 times.

I am not able to debug your SMTP however, you can re-send it automatically:

```python
e = Envelope().message(...).smtp(...)...
if not e.send():
  sleep(1)
  e.send()
```

**Comment by cmh716** [comment]
Thank you for the idea.  The reason why I said that it's not retrying is because the program returns immediately (under 1 second). I would expect at least 50 seconds to pass if it's set to 5 retries with a delay of 10.  Am I incorrect in thinking this would be the behavior?

**Comment by e3rd** [comment]
You are right with the thinking.

This is the line https://github.com/CZ-NIC/envelope/blob/e29d2a5596bc92834c663a8795f9597b8dd5fce1/envelope/smtp_handler.py#L86
that handled the timeout exception and retry. Are you able to add there a print statement so that we can determine what's happening in there?

Something like this:

```python
            except (timeout_exc, SMTPException) as e:
                # this connection is gone, reconnect next time
                del self._instances[self.key]
                print("HERE!", e)  # ADDED
                if isinstance(e, SMTPSenderRefused):
                    logger.warning(
                        f"SMTP sender refused, unable to reconnect. {e}")
                    return False
                elif isinstance(e, timeout_exc):
                    print("HERE TIMEOUT!", e)  # ADDED
                    if self.delay:
                        sleep(self.delay)
                    continue
```


You can add it directly to the smtp_handler.py file which you find that way:

```
$ pip show envelope
Name: envelope
...
Location: /home/.../.local/lib/python3.11/site-packages
```

**Comment by cmh716** [comment]
I added the print statement and I am not seeing it when I hit the error:


Email sent.
Email sent.
SMTP sender refused, unable to reconnect. (421, b'4.4.2 qs51p00im-qukt01071701.me.com Error: timeout exceeded', 'me@icloud.com')
Email sent.
SMTP sender refused, unable to reconnect. (421, b'4.4.2 qs51p00im-qukt01071902.me.com Error: timeout exceeded', 'me@icloud.com')

**Comment by cmh716** [comment]
My current code:

        email = Envelope() \
            .load(original_message.as_bytes()) \
            .to(OUTBOUND_EMAIL) \
            .from_(OUTBOUND_EMAIL) \
            .smtp(SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, "starttls", timeout=45, attempts=5, delay=10) \
            .smime() \
            .signature(Path(KEYFILE), cert=Path(CERTFILE)) \
            .encryption(Path(CERTFILE))

        email_sent = await asyncio.to_thread(email.send)

**Comment by e3rd** [comment]
And if u add a print statement to the sendmessagw method beginning, do you
see ir? So rhat we know your changes work

**Comment by cmh716** [comment]
Sorry, I missed your second print statement. Let me add and retry.

**Comment by e3rd** [comment]
Try changing the line `if isinstance(e, SMTPSenderRefused):` to `if isinstance(e, SMTPAuthenticationError):` please. That might solve all your problems.

It seems I was too strict when handling smtp exceptions.

**Comment by cmh716** [comment]
Yes! thank you so much.  That corrected the issue.  I just hit a failure and there was a delay followed by a successful send, so your retry logic is now working perfectly.

**Comment by e3rd** [comment]
Thanks! I'll commit it to the next release.
