### ISSUE TITLE
validate_email dependency

### ISSUE THREAD

**Issue by tumbl3w33d** [CZ-NIC/envelope#36]
I've been using `envelope` for a few years and last night my CI build broke due to the dependency `validate_email` gone missing:

```
  File "/home/jenkins/agent/workspace/myproject/app.py", line 4, in <module>
    from envelope import Envelope
  File "/usr/local/lib/python/envelope/__init__.py", line 1, in <module>
    from .envelope import Envelope
  File "/usr/local/lib/python/envelope/envelope.py", line 29, in <module>
    from .address import Address
  File "/usr/local/lib/python/envelope/address.py", line 8, in <module>
    from validate_email import validate_email  # noqa, #17 E402, the package name is py3-validate-email
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'validate_email'
```

I went to pypi to figure out the status of that module and noticed there are a few candidates with very different age. Could you elaborate what changed recently that possibly caused this and which module I should install, if I am to fix this on my own?

**Comment by e3rd** [comment]
Strange it happened! The module the envelope uses is https://pypi.org/project/py3-validate-email/ . As I read there, the author decided to leave pypi but the last version seems up and working.

The package name is correctly stated in https://github.com/CZ-NIC/envelope/blob/master/requirements.txt which means *py3-validate-email* should have been correctly installed alongside envelope.

**Comment by tumbl3w33d** [comment]
Alright, thanks for confirming the package name. When I explicitly add that to my requirements.txt in addition to envelope, it works as expected. Might be a bug or change of behavior in the alpine toolchain (which is not exactly python-friendly). I'm building all of this in a multistage dockerfile and there were no errors whatsoever, but it just wouldn't install this dependency.

Adding that explicit dependency is a workaround that I can live with. Thank you for your feedback!

**Comment by e3rd** [comment]
Thanks for having investigated! If that will raise the issue for other people, I'll try to tackle it more.

**Comment by e3rd** [comment]
It was some strange things... 

I had different dependency package versions specified for different Python3.8; some newer releases were declined by Pypi due to licensing (it seems) and hence, when build from Pypi, dependency missed. No, it should work again.
