### ISSUE TITLE
expose smtp.quit() 

### ISSUE THREAD

**Issue by e3rd** [CZ-NIC/envelope#5]
... but how? def smtp will return Envelope() instance. envelope.close()? *envelope.quit()*? envelope.global.smtp.quit()?

**Comment by e3rd** [comment]
`envelope.smtp(quit=True)` ?

**Comment by s-m-e** [comment]
A context manager perhaps?

```python
with Envelope(...) as email:
    email.send()
# or
email = Envelope(...)
with email:
    email.send()
```

This would actually allow a nice API to solve some of the issues in #21 ;) The `email` object (instance of `Envelope`) could, if used as a context, open the SMTP connection independently of sending the mail and automatically close it once the context block is left. This would be really useful.

**Comment by s-m-e** [comment]
As counterparts, I'd rename `def smtp` to `def open_smtp` (and add options to force overriding a cached connection) and give the `Envelope` another `def close_smtp` method. Those could then be utilized by `__enter__` and `__exit__`.

**Comment by e3rd** [comment]
Envelope share SMTP connection amongts instances. Closing it after first e-mail is sent by `with Envelope(...) as email:` would cause next e-mail re-connect.

> rename def smtp to def open_smtp

I think this would increase a little the complexity of the API which I tend to let as simple as possible. However, I'll consider this, many thanks for the contribution.

PS: For anyone that finds this thread, you may pass your custom SMTP object to the .smtp(), mimicking `with Envelope(...) as email:` suggestion by something like:

```python3
smtp = smtplib.SMTP()
with smtp:
    Envelope("message").smtp(smtp).send()
```

**Comment by e3rd** [comment]
`Envelope.smtp_quit()` seems to me the most explicit, short, autocompletable solution now.

* will there be any other resources needed to close in the future? (So that we call it rather Envelope.quit/close.)
* calling it on the instance `Envelope().smtp_quit()` would close only the SMTP instance used for this e-mail to send
* calling it on the class `Envelope.smtp_quit()` would close all the SMTP instances cached and possible still open in utils.SMTP._instances

Any thoughts? Is it elegant or chaotic?

**Comment by s-m-e** [comment]
> calling it on the class Envelope.smtp_quit() would close all the SMTP instances cached and possible still open in utils.SMTP._instances

I would not close **all** cached connections but only those which match the SMTP server url provided to the Envelope object.

**Comment by e3rd** [comment]
calling it on the class means no Envelope object is available :)
* `Envelope.smtp_quit()` → closing all
* `Envelope().smtp_quit()` → closing only those which match the SMTP server url provided to the Envelope object
