### ISSUE TITLE
Feature request: let users decide if PGP subjects are encrypted.

### ISSUE THREAD

**Issue by am47734** [CZ-NIC/envelope#8]
Currently, if an email is to be sent PGP encrypted, the subject is set as "Encrypted message" and the actual subject is passed through to the encrypted part of the email. Unfortunately, not all email clients handle encrypted subjects well, and those that do often decrypt the subject when reading the email, but when looking through the inbox all such emails will remain with the subject "Encrypted message". 

I would like to suggest that we leave the subject and its encryption decision up to the user. After all, the user can always set "Encrypted message" as the clear-text subject if they wish. 

Implementation: It seems that 2 subjects are potentially needed, (1) the subject that is always sent in the clear and shows up how subjects normally do, and (2) a subject for PGP emails to be shown only when the message is decrypted. 

Maybe something like this -- and so the new behavior would look like:

.subject("Encrypted message ")
.subject_pgp("the actual subject that I wanted to send and gets encrypted")

could also do:

.subject("Encrypted message ", subject_pgp="super secret only after decryption!")

subject_pgp would be optional, and if omitted the behavior as it currently stands would happen. 
Thoughts?

**Comment by am47734** [comment]
if subject encryption is also possible with S/MIME then perhaps the naming convention should be "subject_enc" instead of "subject_pgp"?

**Comment by e3rd** [comment]
Thanks for submitting, I'll try to handle this.

**Comment by e3rd** [comment]
I've chosen the following form: `.subject("Encrypted message ", encrypted="super secret only after decryption!")`

Check if that suits your needs. Have a nice day!

**Comment by am47734** [comment]
Perfect! Works great. thank you!
